### ISSUE TITLE
Warning after Sign Up

### ISSUE THREAD

**Issue by jiveRed** [amandeepmittal/expo-firebase#4]
There is a warning after creating a user.

`Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground.`

![Screenshot_20191023-221406_Expo 1](https://user-images.githubusercontent.com/55406937/67402299-fbf40c80-f5e2-11e9-8e00-912396a4fe2e.jpg)

**Comment by amandeepmittal** [comment]
Please go through this [QA on stackoverflow](https://stackoverflow.com/questions/44603362/setting-a-timer-for-a-long-period-of-time-i-e-multiple-minutes) and maybe apply the possible solution for the Expo app.

**Comment by jiveRed** [comment]
Thanks. So base on my understanding this is some what an internal firebase web sdk problem.

One more thing. For the improvement of the sign up process, is it much better not to automatically sign in the user after sign up. I think, that will solve some how the issue on that warning.

**Comment by amandeepmittal** [comment]
Yeah, its related to SDK.I have a follow up tutorial for the steps I have been following in the sign up process.

I am closing this issue for now.
