### ISSUE TITLE
Error handling once disconnected to the network.

### ISSUE THREAD

**Issue by jiveRed** [amandeepmittal/expo-firebase#5]
I can't find any solution to solve the problem when the device is disconnected to the internet. Tried putting the error.code in catch and conditional statement but still the error persist. TIA

![Screenshot_20191025-234301_Expo 1](https://user-images.githubusercontent.com/55406937/67585195-a6099b00-f781-11e9-8b0a-82f7590e9165.jpg)

**Comment by amandeepmittal** [comment]
Hey @jiveRed, Maybe you can add a check using Netinfo module and alert user that they must be connected to a network. I am not going to add this to the repo right now. I am trying to keep this repo (on a personal level) strictly close to the posts/tutorials it is being used as a reference. Thus, I am closing this issue.
